# This is a basic workflow to help you get started with Actions

name: binder-install

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 4 * * 0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create a docker image using repo2docker
      id: install-using-repo2docker
      uses: shankari/repo2docker-action@master
      with:
        IMAGE_NAME: "mobilitynet"

    - name: Verify repo2docker environment
      run: |
        echo "image SHA was ${{ steps.install-using-repo2docker.outputs.IMAGE_SHA_NAME }}"
        echo "Listing all images"
        docker image list

        echo "Checking to see if mobilitynet exists"
        docker image list | grep mobilitynet | wc -l
        echo "Checking to see if repo2docker creation image exists"
        docker image list | grep repo2docker | wc -l

        echo "Reading versions of related software"
        echo "---- DOCKER ----"
        docker --version
        CURR_DOCKER_VER=`docker --version`
        echo "---- CONDA ----"
        docker run ${{ steps.install-using-repo2docker.outputs.IMAGE_SHA_NAME }} /srv/conda/bin/conda --version | cut -d " " -f 2
        CURR_CONDA_VER=`docker run ${{ steps.install-using-repo2docker.outputs.IMAGE_SHA_NAME }} /srv/conda/bin/conda --version | cut -d " " -f 2`
        echo "---- repo2docker----"
        docker run jupyter/repo2docker:master pip3 list | grep jupyter-repo2docker
        CURR_R2D_VER=`docker run jupyter/repo2docker:master pip3 list | grep jupyter-repo2docker`
        echo "On checking, docker ver is $CURR_DOCKER_VER"
        echo "             conda ver is $CURR_CONDA_VER and"
        echo "             repo2docker ver is $CURR_R2D_VER"

    - name: Package the built image
      run: |
        docker save ${{ steps.install-using-repo2docker.outputs.IMAGE_SHA_NAME }} > /tmp/${{ steps.install-using-repo2docker.outputs.IMAGE_SHA_NAME }}.tar

    - name: Save the built image as an artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.install-using-repo2docker.outputs.IMAGE_SHA_NAME }}.tar
        path: /tmp/${{ steps.install-using-repo2docker.outputs.IMAGE_SHA_NAME }}.tar
